[package]
name = "hyperliquid_rust_sdk"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "Rust SDK for Hyperliquid"
homepage = "https://hyperliquid.xyz/"
readme = "README.md"
documentation = "https://github.com/hyperliquid-dex/hyperliquid-rust-sdk"
repository = "https://github.com/hyperliquid-dex/hyperliquid-rust-sdk"

[dependencies]
chrono = "0.4.26"
ethers = {version = "2.0.14", features = ["eip712", "abigen"]}
futures-util = "0.3.28"
lazy_static = "1.3"
log = "0.4.19"
rand = "0.8.5"
reqwest = "0.11.18"
rmp-serde = "1.0.0"
serde = {version = "1.0.175", features = ["derive"]}
serde_json = "1.0.103"
thiserror = "1.0.44"
tokio = {version = "1.29.1", features = ["net", "sync"]}
tokio-tungstenite = {version = "0.20.0", features = ["native-tls"]}
uuid = {version = "1.6.1", features = ["v4"]}

[dev-dependencies]
env_logger = "0.10.0"
tokio = {version = "1.29.1", features = ["full"]}
